const call = new Audio('/audio/call.wav')
call.load()
const      check = new Audio('/audio/check.wav')
      check.load()
      const       raise = new Audio('/audio/raise.wav')
      raise.load()
      const shuffle = new Audio('/audio/shuffle.wav')
      shuffle.load()
      const yourturn = new Audio('/audio/yourturn.wav')
      yourturn.load()