call = new Audio('/audio/call.wav')
call.load()
      check = new Audio('/audio/check.wav')
      check.load()
      raise = new Audio('/audio/raise.wav')
      raise.load()
      shuffle = new Audio('/audio/shuffle.wav')
      shuffle.load()
      .yourturn = new Audio('/audio/yourturn.wav')
      this.yourturn.load()